export const psLinkData = [
  {
    id: 1,
    parent: {
      id: 100,
      name: "Kiran Nune",
      gender: "male",
      image: "https://tailux.piniastudio.com/images/avatar/avatar-16.jpg",
    },
    kids: [
      {
        id: 201,
        name: "Kid One",
        gender: "male",
        image:
          "https://as1.ftcdn.net/v2/jpg/12/24/11/02/1000_F_1224110293_eAwZvkP107TnkF6V8hGkAuI2XvytBXzE.jpg",
        studentId: "STU201",
        admissionNumber: "A201",
        class: "Grade 2",
        section: "A",
        academicYear: "2025-2026",
        courseId: 12,
        dob: "2017-06-10",
        age: 8,
        bloodGroup: "O+",
        nationality: "Indian",
        religion: "Hindu",
        motherTongue: "Telugu",
        addressLine1: "Plot 12, Teachers Colony",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500059",
        branch: "Madhapur Branch",   // ✅ added branch
        progress: 75,
        presenceStatus: "available",
        badges: ["Top Performer", "Math Star"],
        workingHours: { start: "09:00", end: "15:00" },
      },
      {
        id: 202,
        name: "Kid Two",
        gender: "female",
        image:
          "https://as1.ftcdn.net/v2/jpg/15/63/04/46/1000_F_1563044689_TFzh6QGMErEODT01Yc4cs6c1K8jy1fWL.jpg",
        studentId: "STU202",
        admissionNumber: "A202",
        class: "Grade 5",
        section: "B",
        academicYear: "2025-2026",
        courseId: 15,
        dob: "2014-09-23",
        age: 11,
        bloodGroup: "A+",
        nationality: "Indian",
        religion: "Hindu",
        motherTongue: "Telugu",
        addressLine1: "Plot 12, Teachers Colony",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500059",
        branch: "Kukatpally Branch", // ✅ added branch
        progress: 68,
        presenceStatus: "offline",
        badges: ["Science Whiz"],
        workingHours: { start: "08:30", end: "14:30" },
      },
    ],
  },
];
